name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (patch, minor or major)'
        type: choice
        required: true
        default: 'patch'
        options:
          - patch
          - minor
          - major
env:
  GRADLE_FLAGS: >
    -PREPSY_RELEASE_URL=${{ secrets.REPSY_RELEASE_URL }}
    -PREPSY_USER=${{ secrets.REPSY_USER }}
    -PREPSY_PASS=${{ secrets.REPSY_PASS }}

jobs:
    build:
        uses: ./.github/workflows/build.yml

    release:
      runs-on: ubuntu-latest
      environment: Production
      needs: build
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 17

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v4

        - name: Retrieve Current Version
          id: retrieve-current-version
          uses: ./.github/actions/retrieve-current-version

        - name: Calculate next version
          id: calculate-next-version
          uses: ./.github/actions/calculate-next-version
          with:
            current_version: ${{ steps.retrieve-current-version.outputs.current_version }}
            increment_type: ${{ github.event.inputs.release_type }}

        - name: Release and Publish
          run: |
            git config --local user.email "github-actions@github.com"
            git config --local user.name "github-actions"
            release_version=${{ steps.calculate-next-version.outputs.next_version }}
            ./gradlew release $GRADLE_FLAGS -Prelease.releaseVersion=$release_version -Prelease.useAutomaticVersion=true

