name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    build:
        uses: ./.github/workflows/build.yml

    release:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 17

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v4

        - name: Read Version
          id: read-version
          uses: ./.github/actions/read-version

        - name: Create Release
          run: echo "Version is ${{ steps.read-version.outputs.current-version }}"

