name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    build:
        uses: ./.github/workflows/build.yml

    release:
      runs-on: ubuntu-latest
      steps:
        - name: Read Version
          uses: ./.github/actions/read-version
        - run: echo "Version is ${{ env.version }}"

